# https://toml.io/ja/v1.0.0
# 注：TOML は Python ではありませんので、ここでは Python の文法を使用しないでください。
# 例：TOML のブール値は小文字でなければならないです。

[module_weekly]
# モジュールの設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
ysarchives_user_agent = "" # YsArchives Biweekly の RSS を取得するときに使用する User-Agent 文字列です。空欄の場合は既定値を上書きしません。
